### ISSUE TITLE
provide consistent env vars for authentication configuration

### ISSUE THREAD

**Issue by kdelee** [ansible-collections/community.kubernetes#289] opened 2020-11-02 20:50 UTC
##### SUMMARY

some of the modules here support the use of:
```
K8S_AUTH_SSL_CA_CERT
K8S_AUTH_VERIFY_SSL
K8S_AUTH_API_KEY
K8S_AUTH_HOST
```

But not all. The helm modules in particular only seem to support `K8S_AUTH_KUBECONFIG`. Ansible tower greatly prefers handling authentication secrets in env vars rather than files, so we prefer fixing this here by providing the options rather than changing how we inject k8s authentication info into the job environment.

this is a new awx/tower feature, see https://github.com/ansible/awx/issues/5735 if you are not familar.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

helm modules

**Comment by tima** [comment] 2020-11-02 21:27
This is a duplicate of #279

**Closed by tima** 2020-11-02 21:27 UTC
Labels: duplicate
